services:
  # Der Message Broker für die Event-Driven Architecture (EDA)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Standard-Port für Kommunikation
      - "15672:15672" # Dashboard zur Kontrolle

  # Die Schreibseite (Commands)
  feeding-service:
    build: ./write_service
    ports:
      - "5001:5000"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  # Die Leseseite (Queries)
  stats-service:
    build: ./read_service
    ports:
      - "5002:5000"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq